// widget-vue/src/components/RecommendationGrid.vue
<template>
  <Recommendations v-bind="$props" layout="grid" @product-click="emit('product-click', $event)" @product-impression="emit('product-impression', $event)" />
</template>

<script setup lang="ts">
import Recommendations from './Recommendations.vue';
import type { RecommendationProps, Product } from '../types';

interface Props extends Omit<RecommendationProps, 'layout'> {
  className?: string;
  style?: Record<string, any>;
}

defineProps<Props>();

const emit = defineEmits<{
  'product-click': [product: Product];
  'product-impression': [products: Product[]];
}>();
</script>

// widget-react/src/components/RecommendationGrid.tsx
/**
 * Recommendation Grid Component
 */

import React from 'react';
import { Recommendations } from './Recommendations';
import type { RecommendationProps } from '../types';

export interface RecommendationGridProps extends Omit<RecommendationProps, 'layout'> {}

export const RecommendationGrid: React.FC<RecommendationGridProps> = (props) => {
  return <Recommendations {...props} layout="grid" />;
};
